name: vaessl_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.2.1
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=3.3.0
  - brotlipy=0.7.0
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - contextvars=2.4
  - cryptography=3.4.7
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - dataclasses=0.8
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - freetype=2.10.4
  - icu=67.1
  - idna=2.10
  - immutables=0.15
  - importlib-metadata=4.6.1
  - intel-openmp=2021.2.0
  - ipykernel=5.5.5
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jinja2=3.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.9.0
  - jupyterlab=3.0.16
  - jupyterlab_server=2.6.1
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.7
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mistune=0.8.4
  - mkl=2021.2.0
  - nbclassic=0.3.1
  - nbconvert=5.6.1
  - nbformat=5.1.3
  - ncurses=6.2
  - ninja=1.10.2
  - notebook=6.3.0
  - numpy=1.19.5
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=21.0
  - pandoc=2.14.0.3
  - pandocfilters=1.4.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.2
  - prometheus_client=0.11.0
  - prompt_toolkit=1.0.15
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.6.13
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.6.0
  - pytz=2021.1
  - pyzmq=22.1.0
  - readline=8.1
  - requests=2.25.1
  - requests-unixsocket=0.2.0
  - scipy=1.5.3
  - send2trash=1.7.1
  - setuptools=49.6.0
  - simplegeneric=0.8.1
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.36.0
  - terminado=0.10.1
  - testpath=0.5.0
  - tk=8.6.10
  - torchvision=0.7.0
  - tornado=6.1
  - traitlets=4.3.3
  - typing_extensions=3.10.0.0
  - urllib3=1.26.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - wheel=0.36.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - cython==0.29.23
    - pybind11==2.6.2
    - pyroomacoustics==0.3.1
    - pyro-ppl==1.5.0
